name: lstm-env
channels:
  - defaults
dependencies:
  - cartopy=0.18.0
  - joblib=0.16.0
  - json5=0.9.5
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - matplotlib==3.3.0
  - matplotlib-base=3.2.2
  - numpy-base=1.18.5
  - pandas=1.0.5
  - python=3.8.3
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - pip:
    - geomagpy==0.9.8
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - numpy==1.19.5
    - tensorflow==2.4.1
